using System.Globalization;
using ClosedXML.Excel;
using HSMS.Shared.Contracts;

namespace HSMS.Desktop.Reporting;

public static class AnalyticsXlsxExporter
{
    public static void BuildWorkbook(
        IXLWorkbook wb,
        string generatedBy,
        DateTime generatedAtUtc,
        AnalyticsFilterDto filter,
        SterilizationAnalyticsDto analytics,
        BiAnalyticsDto? bi)
    {
        AddMetadataSheet(wb, generatedBy, generatedAtUtc, filter);
        AddTotalsSheet(wb, analytics);
        AddByDaySheet(wb, analytics);
        AddBreakdownsSheet(wb, analytics);
        AddQaSheet(wb, analytics);
        AddBiPaperSheet(wb, analytics);
        AddBiLogsSheet(wb, bi);
        AddBiTrendSheet(wb, bi);
    }

    private static void AddMetadataSheet(IXLWorkbook wb, string generatedBy, DateTime generatedAtUtc, AnalyticsFilterDto filter)
    {
        var ws = wb.Worksheets.Add("Metadata");
        ws.Cell(1, 1).Value = "HSMS Analytics Export";
        ws.Cell(1, 1).Style.Font.Bold = true;
        ws.Cell(1, 1).Style.Font.FontSize = 16;

        var r = 3;
        ws.Cell(r, 1).Value = "Generated By"; ws.Cell(r, 2).Value = generatedBy; r++;
        ws.Cell(r, 1).Value = "Generated At (UTC)"; ws.Cell(r, 2).Value = generatedAtUtc; ws.Cell(r, 2).Style.NumberFormat.Format = "yyyy-mm-dd hh:mm"; r++;
        r++;

        ws.Cell(r, 1).Value = "Applied Filters"; ws.Cell(r, 1).Style.Font.Bold = true; r++;
        WriteFilterRow(ws, ref r, "FromUtc", filter.FromUtc);
        WriteFilterRow(ws, ref r, "ToUtc", filter.ToUtc);
        WriteFilterRow(ws, ref r, "SterilizerId", filter.SterilizerId);
        WriteFilterRow(ws, ref r, "SterilizationType", filter.SterilizationType);
        WriteFilterRow(ws, ref r, "LoadStatus", filter.LoadStatus);
        WriteFilterRow(ws, ref r, "Implants", filter.Implants);
        WriteFilterRow(ws, ref r, "BiLotNo", filter.BiLotNo);
        WriteFilterRow(ws, ref r, "BiResult", filter.BiResult);
        WriteFilterRow(ws, ref r, "Department", filter.Department);
        WriteFilterRow(ws, ref r, "DoctorRoomId", filter.DoctorRoomId);
        WriteFilterRow(ws, ref r, "CycleProgram", filter.CycleProgram);
        WriteFilterRow(ws, ref r, "OperatorName", filter.OperatorName);
        WriteFilterRow(ws, ref r, "GlobalSearch", filter.GlobalSearch);

        ws.Columns().AdjustToContents();
    }

    private static void WriteFilterRow(IXLWorksheet ws, ref int row, string key, object? value)
    {
        if (value is null) return;
        if (value is string s && string.IsNullOrWhiteSpace(s)) return;
        ws.Cell(row, 1).Value = key;
        ws.Cell(row, 2).Value = value switch
        {
            DateTime dt => dt,
            int i => i,
            long l => l,
            decimal d => d,
            double dbl => dbl,
            bool b => b,
            _ => value.ToString() ?? ""
        };
        row++;
    }

    private static void AddTotalsSheet(IXLWorkbook wb, SterilizationAnalyticsDto a)
    {
        var ws = wb.Worksheets.Add("Totals");
        var rows = new (string Key, int Value)[]
        {
            ("Total Loads", a.TotalLoads),
            ("Completed Loads", a.CompletedLoads),
            ("Draft Loads", a.DraftLoads),
            ("Voided Loads", a.VoidedLoads),
            ("Total Pcs", a.TotalPcs),
            ("Total Qty", a.TotalQty)
        };

        ws.Cell(1, 1).Value = "Metric";
        ws.Cell(1, 2).Value = "Value";
        StyleHeader(ws.Range(1, 1, 1, 2));

        for (var i = 0; i < rows.Length; i++)
        {
            ws.Cell(i + 2, 1).Value = rows[i].Key;
            ws.Cell(i + 2, 2).Value = rows[i].Value;
        }

        ws.Columns().AdjustToContents();
        ws.SheetView.FreezeRows(1);
    }

    private static void AddByDaySheet(IXLWorkbook wb, SterilizationAnalyticsDto a)
    {
        var ws = wb.Worksheets.Add("By Day");
        ws.Cell(1, 1).Value = "Day (UTC)";
        ws.Cell(1, 2).Value = "Loads";
        ws.Cell(1, 3).Value = "Pcs";
        ws.Cell(1, 4).Value = "Qty";
        StyleHeader(ws.Range(1, 1, 1, 4));

        var r = 2;
        foreach (var d in (a.ByDay ?? []).OrderBy(x => x.DayUtc))
        {
            ws.Cell(r, 1).Value = d.DayUtc;
            ws.Cell(r, 1).Style.NumberFormat.Format = "yyyy-mm-dd";
            ws.Cell(r, 2).Value = d.Loads;
            ws.Cell(r, 3).Value = d.Pcs;
            ws.Cell(r, 4).Value = d.Qty;
            r++;
        }

        ws.Columns().AdjustToContents();
        ws.SheetView.FreezeRows(1);
        ws.RangeUsed()?.SetAutoFilter();
    }

    private static void AddBreakdownsSheet(IXLWorkbook wb, SterilizationAnalyticsDto a)
    {
        var ws = wb.Worksheets.Add("Breakdowns");
        var sections = new (string Title, IReadOnlyList<AnalyticsBreakdownRowDto> Rows)[]
        {
            ("Sterilization Type", a.BySterilizationType),
            ("BI Result (Header)", a.ByBiResult),
            ("Department (Lines)", a.ByDepartment),
            ("Top Items by Qty", a.TopItemsByQty),
            ("Doctor / Room", a.ByDoctorRoom)
        };

        var r = 1;
        foreach (var (title, rows) in sections)
        {
            ws.Cell(r, 1).Value = title;
            ws.Cell(r, 1).Style.Font.Bold = true;
            r++;

            ws.Cell(r, 1).Value = "Key";
            ws.Cell(r, 2).Value = "Loads/Lines";
            ws.Cell(r, 3).Value = "Pcs";
            ws.Cell(r, 4).Value = "Qty";
            StyleHeader(ws.Range(r, 1, r, 4));
            r++;

            foreach (var x in rows ?? [])
            {
                ws.Cell(r, 1).Value = x.Key;
                ws.Cell(r, 2).Value = x.Loads;
                ws.Cell(r, 3).Value = x.Pcs;
                ws.Cell(r, 4).Value = x.Qty;
                r++;
            }
            r += 2;
        }

        ws.Columns().AdjustToContents();
        ws.SheetView.FreezeRows(1);
    }

    private static void AddQaSheet(IXLWorkbook wb, SterilizationAnalyticsDto a)
    {
        var ws = wb.Worksheets.Add("QA");
        ws.Cell(1, 1).Value = "Metric";
        ws.Cell(1, 2).Value = "Value";
        StyleHeader(ws.Range(1, 1, 1, 2));

        var qa = a.QaTests;
        var rows = qa is null
            ? new (string, int)[] { ("(QA unavailable)", 0) }
            : new[]
            {
                ("Leak Pass", qa.LeakPass),
                ("Leak Fail", qa.LeakFail),
                ("BowieDick Pass", qa.BowiePass),
                ("BowieDick Fail", qa.BowieFail),
                ("Pending Approval", qa.PendingApproval)
            };

        for (var i = 0; i < rows.Length; i++)
        {
            ws.Cell(i + 2, 1).Value = rows[i].Item1;
            ws.Cell(i + 2, 2).Value = rows[i].Item2;
        }
        ws.Columns().AdjustToContents();
        ws.SheetView.FreezeRows(1);
    }

    private static void AddBiPaperSheet(IXLWorkbook wb, SterilizationAnalyticsDto a)
    {
        var ws = wb.Worksheets.Add("BI Paper");
        ws.Cell(1, 1).Value = "Metric";
        ws.Cell(1, 2).Value = "Value";
        StyleHeader(ws.Range(1, 1, 1, 2));

        if (a.BiLogPaper is null)
        {
            ws.Cell(2, 1).Value = "(BI paper analytics unavailable)";
            ws.Columns().AdjustToContents();
            return;
        }

        var b = a.BiLogPaper;
        var rows = new (string, int)[]
        {
            ("Loads In Scope", b.LoadsInScope),
            ("Lot No Captured", b.LotNoCaptured),
            ("Routine Daily Marked", b.RoutineDailyMarked),
            ("BI Time In Captured", b.BiTimeInCaptured),
            ("BI Time Out Captured", b.BiTimeOutCaptured),
            ("BI Times Both Captured", b.BiTimesBothCaptured),
            ("Incubator Reading Checked", b.IncubatorReadingChecked)
        };
        for (var i = 0; i < rows.Length; i++)
        {
            ws.Cell(i + 2, 1).Value = rows[i].Item1;
            ws.Cell(i + 2, 2).Value = rows[i].Item2;
        }
        ws.Columns().AdjustToContents();
        ws.SheetView.FreezeRows(1);
    }

    private static void AddBiLogsSheet(IXLWorkbook wb, BiAnalyticsDto? bi)
    {
        var ws = wb.Worksheets.Add("BI Logs");
        ws.Cell(1, 1).Value = "Key";
        ws.Cell(1, 2).Value = "Total";
        ws.Cell(1, 3).Value = "Pass";
        ws.Cell(1, 4).Value = "Fail";
        ws.Cell(1, 5).Value = "Pending";
        ws.Cell(1, 6).Value = "Missing";
        StyleHeader(ws.Range(1, 1, 1, 6));

        if (bi is null)
        {
            ws.Cell(2, 1).Value = "(BI analytics unavailable)";
            ws.Columns().AdjustToContents();
            return;
        }

        var r = 2;
        foreach (var x in bi.BySterilizer ?? [])
        {
            ws.Cell(r, 1).Value = $"Sterilizer: {x.Key}";
            ws.Cell(r, 2).Value = x.Total;
            ws.Cell(r, 3).Value = x.Pass;
            ws.Cell(r, 4).Value = x.Fail;
            ws.Cell(r, 5).Value = x.Pending;
            ws.Cell(r, 6).Value = x.Missing;
            r++;
        }

        ws.Columns().AdjustToContents();
        ws.SheetView.FreezeRows(1);
        ws.RangeUsed()?.SetAutoFilter();
    }

    private static void AddBiTrendSheet(IXLWorkbook wb, BiAnalyticsDto? bi)
    {
        var ws = wb.Worksheets.Add("Trend Data");
        ws.Cell(1, 1).Value = "Day (UTC)";
        ws.Cell(1, 2).Value = "Total";
        ws.Cell(1, 3).Value = "Pass";
        ws.Cell(1, 4).Value = "Fail";
        ws.Cell(1, 5).Value = "Pending";
        ws.Cell(1, 6).Value = "Missing";
        StyleHeader(ws.Range(1, 1, 1, 6));

        if (bi is null)
        {
            ws.Cell(2, 1).Value = "(BI analytics unavailable)";
            ws.Columns().AdjustToContents();
            return;
        }

        var r = 2;
        foreach (var d in (bi.ByDay ?? []).OrderBy(x => x.DayUtc))
        {
            ws.Cell(r, 1).Value = d.DayUtc;
            ws.Cell(r, 1).Style.NumberFormat.Format = "yyyy-mm-dd";
            ws.Cell(r, 2).Value = d.Total;
            ws.Cell(r, 3).Value = d.Pass;
            ws.Cell(r, 4).Value = d.Fail;
            ws.Cell(r, 5).Value = d.Pending;
            ws.Cell(r, 6).Value = d.Missing;
            r++;
        }

        ws.Columns().AdjustToContents();
        ws.SheetView.FreezeRows(1);
        ws.RangeUsed()?.SetAutoFilter();
    }

    private static void StyleHeader(IXLRange range)
    {
        range.Style.Font.Bold = true;
        range.Style.Fill.BackgroundColor = XLColor.FromArgb(0xEE, 0xF6, 0xFF);
        range.Style.Border.BottomBorder = XLBorderStyleValues.Thin;
        range.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
    }
}

